#!/usr/bin/env python
#
# $Id$
#

import re, os
from distutils.core import setup

setup(name="honeysnap",
      version="1.0rc2",
      author="Jed Hale",
      author_email="jed.haile@thelogangroup.biz",  
      maintainer="Arthur Clune",
      maintainer_email="arthur@honeynet.org.uk",
      url="http://www.honeynet.org/tools/honeysnap", 
      description="A tool for analysing pcap files",
      long_description="Honeysnap helps an analyst with the task of analysing pcap files generated by a honeypot",
	  license="GNU GPL",
      packages=["honeysnap"],
      scripts = ['scripts/honeysnap'],
      )
